<?php

namespace ALT\AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Création du querybuilder pour l'entité "Commentaire"
     * On veut récupérer le  nombre de commentaires via la fonction COUNT()
     * 
     * On retourne le résultat du comptage 
     * 
     * @return mixed
     */
    public function countNbCommentaires()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->select('COUNT(c.id)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Création du querybuilder pour l'entité "Commentaire"
     * On veut récupérer le  nombre de commentaire via la fonction COUNT()
     * et sélectionner seulement les commentaire où signale = 1
     *
     * On retourne le résultat du comptage
     * 
     * @return mixed
     */
    public function countNbCommentairesSignales()
    {
        $qb = $this->createQueryBuilder('c'); 
        $qb
            ->andWhere($qb->expr()->in('c.signale', 1))
            ->select('COUNT(c.id)'); 

        return $qb->getQuery()->getSingleScalarResult(); 
    }

    /**
     * Création du querybuilder pour l'entité "Commentaire"
     * pour récupérer des commentaires depuis notre base de données, triés par "id" en ordre descendant.
     * 
     * Si on a un filtre ....
     * 
     * On retourne le résultat 
     * 
     * @param null $filtre
     * @param null $billet
     * @return array
     * @throws \Exception
     */
    public function listeCommentaires($filtre = null, $billet = null)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->orderBy('c.id', 'desc');

        if (isset($filtre)) { // Si on a un filtre dans l'URL
            switch ($filtre) { // On regarde quel filtre on demande :
                case 'signaler': // Si on ne veut que les commentaires "signalés"
                    $qb->andWhere('c.signale = 1');
                    break;
                case 'billet': // Si on ne veut que les commentaires d'un billet en particulier
                    if (!isset($billet)) {
                        throw new \Exception("Billet obligatoire pour la recherche via un billet spécifique");
                    }

                    $qb->andWhere('c.billet = :billet'); // On attache le billet à la condition pour récupérer les commentaires
                    $qb->setParameter('billet', $billet);
                    break;
            }
        }

        return $qb->getQuery()->getResult();
    }
    
    
}
