# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
  encoders:
    ALT\UserBundle\Entity\User:
        algorithm: sha512
        iterations: 1
        encode_as_base64: false

  role_hierarchy:
     ROLE_ADMIN:  [ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
      main:
          entity:
              class: ALT\UserBundle\Entity\User
              property: username

  firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

    main:
        pattern:      ^/
        anonymous:    true
        provider:     main
        form_login:
           login_path: login
           check_path: login_check
           default_target_path: /admin
        logout:
           path:       logout
           target:     /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

  access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

