alt_app_contact:
    path:     /contact
    defaults:
        _controller: ALTAppBundle:Contact:contact


alt_app_lecture:
    path:    /lecture/{id}
    defaults:
        _controller: ALTAppBundle:Billet:lecture
    requirements:
        id: \d+

alt_app_ajouter_commentaire:
    path:     /billet/{id}/ajouter_commentaire
    defaults:
        _controller: ALTAppBundle:Commentaires:ajouterCommentaire

alt_app_repondre_commentaire:
    path:     /commentaire/{id}/repondre_commentaire
    defaults:
        _controller: ALTAppBundle:Commentaires:repondreCommentaire

alt_app_signaler_commentaire:
    path: /commentaire/{id}/signaler
    defaults:
         _controller: ALTAppBundle:Commentaires:signaler

alt_app_admin_ajouter:
    path:      /admin/billet/ajouter
    defaults:
        _controller: ALTAppBundle:Admin:ajouter

alt_app_admin_modifier:
    path:      /admin/billet/{id}/modifier
    defaults:
        _controller: ALTAppBundle:Admin:modifier
    requirements:
        id: \d+

alt_app_admin_modifier_commentaire:
    path:      /admin/commentaire/{id}/modifier_commentaire
    defaults:
        _controller: ALTAppBundle:Admin:modifierCommentaire
    requirements:
        id: \d+

alt_app_admin_supprimer_commentaire:
    path:      /admin/commentaire/{id}/supprimer
    defaults:
        _controller: ALTAppBundle:Admin:supprimerCommentaire
    requirements:
        id: \d+

alt_app_admin_valider_commentaire:
    path:      /admin/commentaire/{id}/valider
    defaults:
        _controller: ALTAppBundle:Admin:validerCommentaire
    requirements:
        id: \d+

alt_app_admin_supprimer:
    path:      /admin/billet/{id}/supprimer
    defaults:
        _controller: ALTAppBundle:Admin:supprimer
    requirements:
        id: \d+

alt_app_admin_accueil:
    path: /admin
    defaults:
        _controller: ALTAppBundle:Admin:accueil

alt_app_admin_lecture:
    path:    /admin/billet/{id}
    defaults:
        _controller: ALTAppBundle:Admin:lecture
    requirements:
        id: \d+

alt_app_admin_liste_billets:
    path: /admin/billets/liste
    defaults:
        _controller: ALTAppBundle:Admin:listeBillets

alt_app_admin_liste_contacts:
    path: /admin/contacts/liste
    defaults:
        _controller: ALTAppBundle:Admin:listeContacts

alt_app_admin_liste_commentaires:
    path: /admin/commentaires/liste
    defaults:
        _controller: ALTAppBundle:Admin:listeCommentaires

alt_app_admin_liste_commentaires_par_id:
    path: /admin/commentaires/liste/{id}
    defaults:
        _controller: ALTAppBundle:Admin:listeCommentairesParId
    requirements:
        id: \d+

alt_app_admin_publier_billet:
    path:    /admin/billet/{id}/publier
    defaults:
        _controller: ALTAppBundle:Admin:publierBillet
    requirements:
        id: \d+

alt_app_admin_depublier_billet:
    path:    /admin/billet/{id}/depublier
    defaults:
        _controller: ALTAppBundle:Admin:depublierBillet
    requirements:
        id: \d+

alt_app_admin_contact_repondre:
    path:     /admin/contact/{id}/repondre
    defaults:
        _controller: ALTAppBundle:Admin:reponseContact
    requirements:
        id: \d+

alt_app_admin_contact_lecture:
    path:     /admin/contact/{id}/lecture
    defaults:
        _controller: ALTAppBundle:Admin:lectureContactReponse
    requirements:
        id: \d+


alt_app_homepage:
    path:     /{page}
    defaults:
        _controller: ALTAppBundle:Front:accueil
        page: 1
    requirements:
        id: \d+